/**:
  ros__parameters:
    camera_info_url: package://light_bringup/config/camera_info.yaml
    camera_name: narrow_stereo
    exposure_time: 11000  # 6000 15000
    gain: 10.0


    # exposure_time: 2500
    # gain: 15.0
    # resolution_width: 1280
    # resolution_height: 1024
    # offsetX: 0
    # offsetY: 0
    # recording: false    #是否录制
